### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by vantsymbalenko** [vasturiano/react-force-graph#87]
Does current version provide typescript support?

**Comment by qasimalbaqali** [comment]
By luck I was going through the `node_modules` files in my project and I stumbled upon a types file! Turns out there is already a DefinetlyTyped contribution for the `force-graph` library, which what `react-force-graph` extends to make it React compatible. [https://www.npmjs.com/package/@types/force-graph](https://www.npmjs.com/package/@types/force-graph)!

I installed it in my project and the way I am using it is

```
import ForceGraph2D from "react-force-graph-2d";
import ForceGraph from "force-graph";

class MyGraph extends Component {
  private graphRef: React.RefObject<ForceGraph.ForceGraphInstance> = React.createRef();

  render () {
    return (
      <ForceGraph2D ref={this.graphRef} />
    )
  }
}
```

Seems to work fine :+1:  Not sure about how I am using it tho, since types should be automatically be resolved by Typescript but for some reason this isn't happening for me, and I need to import `ForeGraph` and reference the interface.

**Comment by vcshih** [comment]
@qasimalbaqali can you explain how you got this to work? I have installed `force-graph`, `@types/force-graph`, and `react-force-graph-2d`, but I still get an error that says
```
Could not find a declaration file for module 'react-force-graph-2d'. '/Users/victorshih/System/Github/System/betta-beta/node_modules/react-force-graph-2d/dist/react-force-graph-2d.common.js' implicitly has an 'any' type.
  Try `npm install @types/react-force-graph-2d` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-force-graph-2d';`  TS7016
```

the code I am trying to run is as follows:
```
import React from 'react';
import logo from './logo.gif';
import './App.css';
import ForceGraph2D from 'react-force-graph-2d';
import ForceGraph from 'force-graph';


const App: React.FC = () => {
  const graphRef: React.RefObject<ForceGraph.ForceGraphInstance> = React.createRef();
  return (
    <div className="App">
      <ForceGraph2D ref={graphRef} />
    </div>
  );
}

export default App;
```

I'm pretty new to typescript so the transition has been rough haha

**Comment by vasturiano** [comment]
By popular demand, as of the latest version (`1.31.0`) this library now includes TypeScript declaration files. 🎉 

They are published to NPM together with the modules and available via the `types` entrypoint, for example: https://unpkg.com/react-force-graph-3d/dist/react-force-graph-3d.d.ts
